CREATE TABLE Unit_system
(
Unit_system_id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000  CONSTRAINT Unit_system_pk PRIMARY KEY,
name VARCHAR2(40) NOT NULL
);

CREATE TABLE Unit
(
Unit_id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000  CONSTRAINT Unit_pk PRIMARY KEY,
Unit_system_id NUMBER(4) NOT NULL CONSTRAINT Unit_Unit_system_fk REFERENCES Unit_system (Unit_system_id),
Name VARCHAR2(40) NOT NULL,
Liter_per_unit_ratio NUMBER(7,2) NOT NULL,
Table_spoon_per_unit_ratio NUMBER(7,2) NOT NULL,
Tea_spoon_per_unit_ratio NUMBER(7,2) NOT NULL,
Glass_per_unit_ratio NUMBER(7,2) NOT NULL,
Gram_per_unit_ratio NUMBER(7,2) NOT NULL
);