CREATE TABLE Unit_system
(
Unit_system_id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000  CONSTRAINT Unit_system_pk PRIMARY KEY,
name VARCHAR2(40) NOT NULL
);

CREATE TABLE Unit
(
Unit_id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000  CONSTRAINT Unit_pk PRIMARY KEY,
Unit_system_id NUMBER(4) NOT NULL CONSTRAINT Unit_Unit_system_fk REFERENCES Unit_system (Unit_system_id),
Name VARCHAR2(40) NOT NULL,
Liter_per_unit_ratio NUMBER(7,2) NOT NULL,
Table_spoon_per_unit_ratio NUMBER(7,2) NOT NULL,
Tea_spoon_per_unit_ratio NUMBER(7,2) NOT NULL,
Glass_per_unit_ratio NUMBER(7,2) NOT NULL,
Gram_per_unit_ratio NUMBER(7,2) NOT NULL
);

drop table USERS;
create table USERS
(
    USER_ID number(4) generated by default on null as identity constraint USER_PK primary key,
    USERNAME varchar2(40) not null,
    PASSWORD varchar2(40) not null,
    UNIT_SYSTEM_ID number(4) constraint USER_UNIT_SYSTEM_FK references UNIT_SYSTEM (UNIT_SYSTEM_ID)
);

drop table FOLLOWED;
create table FOLLOWED
(
    FOLLOWED_ID number(4) generated by default on null as identity constraint FOLLOWED_PK primary key,
    FOLLOWING_USER_ID number(4) not null constraint FOLLOWING_USER_FK references USERS (USER_ID),
    FOLLOWED_USER_ID number(4) not null constraint FOLLOWED_USER_FK references USERS (USER_ID)
);