insert into USERS values (null, 'BerryRootUser', 'BerryHardPassword', null);
insert into USERS values (null, 'David', '470646', null);
insert into USERS values (null, 'Alex', '451546', null);
insert into USERS values (null, 'Maria', '438485', null);
insert into USERS values (null, 'Anna', '387660', null);
insert into USERS values (null, 'Marco', '352629', null);
insert into USERS values (null, 'Antonio', '325085', null);
insert into USERS values (null, 'Daniel', '310096', null);
insert into USERS values (null, 'Andrea', '305442', null);
insert into USERS values (null, 'Laura', '296627', null);
insert into USERS values (null, 'Ali', '290285', null);
commit;